/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.View;
import com.Model.*;
/**
 *
 * @author User
 */
public class EmployeeMenu extends javax.swing.JFrame {

    private Cinema cine;
    private Employee user;
    /**
     * Creates new form EmployeeMenu
     */
    public EmployeeMenu(Employee user , Cinema cine) {
        this.user=user;
        this.cine=cine;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        updateFilmButton = new javax.swing.JButton();
        PromotionButton = new javax.swing.JButton();
        updateCustomerButton = new javax.swing.JButton();
        showMovieButton = new javax.swing.JButton();
        retrunButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu");

        updateFilmButton.setText("update films currently playes");
        updateFilmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFilmButtonActionPerformed(evt);
            }
        });

        PromotionButton.setText("apply promotion");
        PromotionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromotionButtonActionPerformed(evt);
            }
        });

        updateCustomerButton.setText("update customer database");
        updateCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerButtonActionPerformed(evt);
            }
        });

        showMovieButton.setText("show populat movie");
        showMovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMovieButtonActionPerformed(evt);
            }
        });

        retrunButton.setText("retrun");
        retrunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrunButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(retrunButton)
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateFilmButton, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(PromotionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showMovieButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(retrunButton))
                .addGap(60, 60, 60)
                .addComponent(updateFilmButton)
                .addGap(32, 32, 32)
                .addComponent(PromotionButton)
                .addGap(31, 31, 31)
                .addComponent(updateCustomerButton)
                .addGap(18, 18, 18)
                .addComponent(showMovieButton)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retrunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrunButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_retrunButtonActionPerformed

    private void updateFilmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFilmButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        UpdateMovie up = new UpdateMovie(user,cine);
        up.setVisible(true);
    }//GEN-LAST:event_updateFilmButtonActionPerformed

    private void PromotionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromotionButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        addPromoFrame promo = new addPromoFrame(user,cine);
        promo.setVisible(true);
    }//GEN-LAST:event_PromotionButtonActionPerformed

    private void updateCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        UpdateDataBaseCustomer frame = new UpdateDataBaseCustomer(user,cine);
        frame.setVisible(true);
       
    }//GEN-LAST:event_updateCustomerButtonActionPerformed

    private void showMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMovieButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        topMoviePanel top = new topMoviePanel(user,cine);
        top.setVisible(true);
    }//GEN-LAST:event_showMovieButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PromotionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton retrunButton;
    private javax.swing.JButton showMovieButton;
    private javax.swing.JButton updateCustomerButton;
    private javax.swing.JButton updateFilmButton;
    // End of variables declaration//GEN-END:variables
}
