/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.View;
import com.Model.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class UpdateMovie extends javax.swing.JFrame {

     private Cinema cine;
     private Employee user;
    /**
     * Creates new form UpdateMovie
     */
    public UpdateMovie(Employee user , Cinema cine) {
        this.user=user;
        this.cine=cine;
        initComponents();
        movie1.setText(cine.getFilms().get(0).getName());
        movie2.setText(cine.getFilms().get(1).getName());
        movie3.setText(cine.getFilms().get(2).getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nomTF = new javax.swing.JTextField();
        genreTF = new javax.swing.JTextField();
        imageTF = new javax.swing.JTextField();
        dateTF = new javax.swing.JTextField();
        dureeTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        movie1 = new javax.swing.JRadioButton();
        movie2 = new javax.swing.JRadioButton();
        movie3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        returnButton = new javax.swing.JToggleButton();
        validationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("new movie date");

        imageTF.setText("image/");

        dureeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dureeTFActionPerformed(evt);
            }
        });

        jLabel2.setText("name : ");

        jLabel3.setText("genre : ");

        jLabel4.setText("image : ");

        jLabel5.setText("release date : ");

        jLabel6.setText("running time : ");

        buttonGroup1.add(movie1);
        movie1.setText("jRadioButton1");

        buttonGroup1.add(movie2);
        movie2.setText("jRadioButton2");

        buttonGroup1.add(movie3);
        movie3.setText("jRadioButton3");

        jLabel7.setText("movie to be deleted");

        returnButton.setText("return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        validationButton.setText("OK");
        validationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movie2)
                            .addComponent(movie1)
                            .addComponent(movie3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(returnButton)))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dureeTF)
                            .addComponent(dateTF)
                            .addComponent(genreTF)
                            .addComponent(imageTF)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1)
                                    .addComponent(nomTF, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(validationButton)
                .addGap(268, 268, 268))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(returnButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(genreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dureeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(jLabel7)
                .addGap(48, 48, 48)
                .addComponent(movie1)
                .addGap(18, 18, 18)
                .addComponent(movie2)
                .addGap(18, 18, 18)
                .addComponent(movie3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(validationButton)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dureeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dureeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dureeTFActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        EmployeeMenu emp= new EmployeeMenu(user,cine);
        emp.setVisible(true);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void validationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validationButtonActionPerformed
        // TODO add your handling code here:       
        try
        {
            String nom = nomTF.getText();
            String image = imageTF.getText();
            String genre = genreTF.getText();
            int duree = Integer.parseInt(dureeTF.getText());
            String date = dateTF.getText();
            if(movie1.isSelected())
            {
                Movie movie = new Movie(nom, genre, date, duree, 0, image);
                cine.getFilms().remove(0);
                cine.getFilms().add(movie);
                movie.addToDataBase();
                cine.saveCurrentMovie();
                this.setVisible(false);
                EmployeeMenu emp= new EmployeeMenu(user,cine);
                emp.setVisible(true);
            }
            else if(movie2.isSelected())
            {
                Movie movie = new Movie(nom, genre, date, duree, 0, image);
                cine.getFilms().remove(1);
                cine.getFilms().add(movie);
                movie.addToDataBase();
                cine.saveCurrentMovie();
                this.setVisible(false);
                EmployeeMenu emp= new EmployeeMenu(user,cine);
                emp.setVisible(true);
            }
            else if(movie3.isSelected())
            {
                Movie movie = new Movie(nom, genre, date, duree, 0, image);
                cine.getFilms().remove(2);
                cine.getFilms().add(movie);
                movie.addToDataBase();
                cine.saveCurrentMovie();
                this.setVisible(false);
                EmployeeMenu emp= new EmployeeMenu(user,cine);
                emp.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Selectionner le film a retirer");
            }
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Vous n'avez pas rempli tous les champs");           
        }      
    }//GEN-LAST:event_validationButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dateTF;
    private javax.swing.JTextField dureeTF;
    private javax.swing.JTextField genreTF;
    private javax.swing.JTextField imageTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton movie1;
    private javax.swing.JRadioButton movie2;
    private javax.swing.JRadioButton movie3;
    private javax.swing.JTextField nomTF;
    private javax.swing.JToggleButton returnButton;
    private javax.swing.JButton validationButton;
    // End of variables declaration//GEN-END:variables
}
